//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminCharge
    {
        public int AdminChargesId { get; set; }
        public string ChargeType { get; set; }
        public string Name { get; set; }
        public decimal Value { get; set; }
        public string ShortName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public Nullable<System.DateTime> UpdatedOnUtc { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public int CustomerId { get; set; }
        public bool IsActive { get; set; }
        public int OperationZoneId { get; set; }
        public string CurrencyCode { get; set; }
    }
}
