//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentAssociatedUser
    {
        public int AgentAssociatedUserId { get; set; }
        public int AgentId { get; set; }
        public string UserType { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string TelephoneNo { get; set; }
        public System.TimeSpan WorkingStartTime { get; set; }
        public System.TimeSpan WorkingEndTime { get; set; }
        public string WorkingWeekDays { get; set; }
    }
}
