//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airline
    {
        public int AirlineId { get; set; }
        public string AirLineName { get; set; }
        public string AirlineCode { get; set; }
        public string CarrierCode2 { get; set; }
        public string CarrierCode3 { get; set; }
        public int CountryId { get; set; }
    }
}
