//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiErrorCode
    {
        public int ErrorCodeId { get; set; }
        public Nullable<int> ErrorCode { get; set; }
        public string Description { get; set; }
        public string DevelopmentErrorDetail { get; set; }
        public string Courier { get; set; }
        public string CourierErrorCode { get; set; }
        public string CourierErrorDescription { get; set; }
        public Nullable<int> ParentErrorCodeId { get; set; }
    }
}
