//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BagManifestTracking
    {
        public int BagManifestTrackingId { get; set; }
        public Nullable<int> BagId { get; set; }
        public Nullable<int> ManifestId { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<bool> IsMissing { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public int MobileEventConfigurationId { get; set; }
        public string Description { get; set; }
    }
}
