//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public int BankId { get; set; }
        public string Name { get; set; }
        public string AccountNumber { get; set; }
        public string SortCode { get; set; }
        public string IBANCode { get; set; }
        public string SwiftCode { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string PostCode { get; set; }
        public string State { get; set; }
        public int CountryId { get; set; }
    }
}
