//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BBKShipmentDetail
    {
        public int BreakBulkShipmentDetailId { get; set; }
        public int BreakBulkShipmentId { get; set; }
        public int PurchaseOrderId { get; set; }
        public int PurchaseOrderDetailId { get; set; }
        public int NoOfCartonPerJob { get; set; }
        public int TotWeightPerJob { get; set; }
        public int ProductCatalogId { get; set; }
        public string CartonName { get; set; }
        public int CartonLength { get; set; }
        public int CartonHeight { get; set; }
        public int CartonWidth { get; set; }
        public int CartonSpecificationId { get; set; }
        public int PONumber { get; set; }
        public int JobNumber { get; set; }
        public int CartonQTY { get; set; }
    }
}
