//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartonSpecification
    {
        public int CartonSpecificationId { get; set; }
        public int FactoryUserId { get; set; }
        public string CartonName { get; set; }
        public int CartonLength { get; set; }
        public int CartonHeight { get; set; }
        public int CartonWidth { get; set; }
    }
}
