//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryShipmentPort
    {
        public int CountryShipmentPortId { get; set; }
        public string PortName { get; set; }
        public string PortCode { get; set; }
        public string PortType { get; set; }
        public int CountryId { get; set; }
    }
}
