//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryLogistic
    {
        public int CountryLogisticId { get; set; }
        public int CountryId { get; set; }
        public string LogisticService { get; set; }
        public string LogisicServiceDisplay { get; set; }
        public string AccountId { get; set; }
        public string AccountNo { get; set; }
        public string CountryCode { get; set; }
        public string Description { get; set; }
    }
}
