//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courier
    {
        public int CourierId { get; set; }
        public string CourierName { get; set; }
        public string DisplayName { get; set; }
        public string Website { get; set; }
        public System.TimeSpan LatestBookingTime { get; set; }
        public string ShipmentType { get; set; }
    }
}
