//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSettingDetail
    {
        public int CustomerSettingDetailId { get; set; }
        public int CustomerSettingId { get; set; }
        public int CourierId { get; set; }
    }
}
