//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSetting
    {
        public int CustomerSettingId { get; set; }
        public int UserId { get; set; }
        public string ScheduleSetting { get; set; }
        public string ScheduleType { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public string ScheduleDay { get; set; }
        public System.TimeSpan ScheduleTime { get; set; }
        public string AdditionalMails { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string ScheduleSettingType { get; set; }
        public Nullable<bool> IsPdf { get; set; }
        public Nullable<bool> IsExcel { get; set; }
    }
}
