//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCompanyDetail
    {
        public int CustomerCompanyDetailId { get; set; }
        public int UserId { get; set; }
        public string LogoFileName { get; set; }
        public string SMTPHostName { get; set; }
        public string SMTPport { get; set; }
        public string SMTPUserName { get; set; }
        public string SMTPPassword { get; set; }
        public string SMTPDisplayName { get; set; }
        public string SMTPFromMail { get; set; }
        public string SMTPEnableSsl { get; set; }
        public string Website { get; set; }
        public string KindRegards { get; set; }
        public string TrackingUrl { get; set; }
        public string RecoveryLink { get; set; }
        public string SiteLink { get; set; }
        public string SiteAddress { get; set; }
        public string OperationStaff { get; set; }
        public string OperationStaffPhone { get; set; }
        public string UserPosition { get; set; }
        public string OperationStaffEmail { get; set; }
        public string SalesStaff { get; set; }
        public string SalesStaffEmail { get; set; }
        public string TrackingEmail { get; set; }
        public string CustomerService { get; set; }
        public string CompanyName { get; set; }
        public string MainWebsite { get; set; }
        public string DocumentSiteLogical { get; set; }
        public string DocumentSitePhysical { get; set; }
    }
}
