//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAdvanceMarginCost
    {
        public int CustomerAdvanceMarginCostId { get; set; }
        public int CustomerId { get; set; }
        public int OperationZoneId { get; set; }
        public int LogisticServiceZoneId { get; set; }
        public int LogisticServiceWeightId { get; set; }
        public int LogisticServiceShipmentTypeId { get; set; }
        public decimal AdvancePercentage { get; set; }
        public string ModuleType { get; set; }
    }
}
