//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMarginOption
    {
        public int CustomerMarginOptionId { get; set; }
        public int OperationZoneId { get; set; }
        public string LogisticCompany { get; set; }
        public string LogisticCompanyDisplay { get; set; }
        public string Options { get; set; }
        public string OptionsDisplay { get; set; }
        public string ShipmentType { get; set; }
        public string ShipmentTypeDisplayText { get; set; }
        public decimal MarginPercentage { get; set; }
    }
}
