//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectShipment
    {
        public int DirectShipmentId { get; set; }
        public int OpearionZoneId { get; set; }
        public int ShipmentStatusId { get; set; }
        public int CustomerId { get; set; }
        public int FromAddressId { get; set; }
        public int ToAddressId { get; set; }
        public string PaymentPartyTaxAndDuties { get; set; }
        public string PaymentPartyTaxAndDutiesAccountNo { get; set; }
        public string Reference1 { get; set; }
        public string Reference2 { get; set; }
        public string SpecialInstruction { get; set; }
        public string ContentDescription { get; set; }
        public Nullable<System.TimeSpan> CollectionTime { get; set; }
        public Nullable<System.DateTime> CollectionDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public int ShipmentTypeId { get; set; }
        public Nullable<decimal> BaseRate { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public Nullable<decimal> FuelSurCharge { get; set; }
        public Nullable<decimal> AdditionalSurcharge { get; set; }
        public Nullable<decimal> FuelSurchargePercent { get; set; }
        public Nullable<System.DateTime> FuelMonthYear { get; set; }
        public string ParcelType { get; set; }
        public Nullable<bool> IsPODMailSent { get; set; }
        public int CourierAccountId { get; set; }
        public string LogisticType { get; set; }
        public string LogisticServiceType { get; set; }
        public string CurrencyCode { get; set; }
        public string TrackingDetail { get; set; }
        public string PackageCaculatonType { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.TimeSpan> DeliveryTime { get; set; }
        public string SignedBy { get; set; }
        public string TaxAndDutiesAcceptedBy { get; set; }
        public string FrayteNumber { get; set; }
        public Nullable<int> ManifestId { get; set; }
        public string AddressType { get; set; }
        public string LogisticLabel { get; set; }
        public string PickUpRef { get; set; }
        public string ShipmentImage { get; set; }
        public Nullable<int> SessionId { get; set; }
        public Nullable<decimal> ChargeableWeight { get; set; }
        public Nullable<System.DateTime> PODMailSentOn { get; set; }
    }
}
