//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectShipmentDetailDraft
    {
        public int DirectShipmentDetailDraftId { get; set; }
        public int DirectShipmentDraftId { get; set; }
        public Nullable<decimal> DeclaredValue { get; set; }
        public Nullable<int> CartoonValue { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public string HSCode { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string PiecesContent { get; set; }
    }
}
