//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectBulkUploadSession
    {
        public int SessionId { get; set; }
        public string SessionName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> TotalShipments { get; set; }
        public string SessionStatus { get; set; }
        public Nullable<System.DateTime> PrintedOn { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> IsSessionPrint { get; set; }
    }
}
