//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectShipmentDetail
    {
        public int DirectShipmentDetailId { get; set; }
        public int DirectShipmentId { get; set; }
        public Nullable<decimal> DeclaredValue { get; set; }
        public int CartoonValue { get; set; }
        public decimal Weight { get; set; }
        public decimal Length { get; set; }
        public decimal Width { get; set; }
        public decimal Height { get; set; }
        public string PiecesContent { get; set; }
    }
}
