//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectShipmentTracking
    {
        public int DirectShipmentTrackingId { get; set; }
        public int DirectShipmentId { get; set; }
        public string TrackingDescription { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public string Location { get; set; }
    }
}
