//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class eCommerceUserCreditNote
    {
        public int eCommerceUserCreditNoteId { get; set; }
        public string CreditNoteReference { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string CurrencyCode { get; set; }
        public int IssuedBy { get; set; }
        public System.DateTime IssuedOnUtc { get; set; }
        public Nullable<System.DateTime> UsedOnUtc { get; set; }
        public string IssuedTo { get; set; }
        public string Status { get; set; }
        public int ShipmentId { get; set; }
        public Nullable<int> eCommreceInvoiceId { get; set; }
    }
}
