//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class eCommerceBag
    {
        public int eCommerceBagId { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> eCommerceBagManiferstId { get; set; }
    }
}
