//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class eCommerceInvoice
    {
        public int InvoiceId { get; set; }
        public string InvoiceRef { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public int ShipmentId { get; set; }
        public decimal TotalDuty { get; set; }
        public int TotalDeclaration { get; set; }
        public decimal TotalVAT { get; set; }
        public decimal AdminSpecClearServ { get; set; }
        public decimal AdminDisbursement { get; set; }
        public decimal TotalAdminVAT { get; set; }
        public decimal OtherLevy { get; set; }
        public string CurrencyCode { get; set; }
        public string InvoiceFullName { get; set; }
        public Nullable<System.DateTime> InvoiceDueDateUtc { get; set; }
        public string Status { get; set; }
        public bool IsPrimary { get; set; }
        public Nullable<decimal> TotalFreeStorageCharge { get; set; }
    }
}
