//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class eCommerceInvoiceTransaction
    {
        public int eCommerceInvoiceTransactionId { get; set; }
        public string PaidBy { get; set; }
        public int InvoiceId { get; set; }
        public decimal PaidAmount { get; set; }
        public System.DateTime PaidOnUtc { get; set; }
        public string PaymentMode { get; set; }
    }
}
