//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class eCommerceEmailCommuniation
    {
        public int eCommerceEmailCommunicationId { get; set; }
        public string EmailSubject { get; set; }
        public string EmailBody { get; set; }
        public int ShipmentId { get; set; }
        public string SentTo { get; set; }
        public System.DateTime EmailSentOnUtc { get; set; }
        public string CC { get; set; }
        public string BCC { get; set; }
        public int SentBy { get; set; }
    }
}
