//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class eCommerceTracking
    {
        public int eCommerceTrackingId { get; set; }
        public int eCommerceShipmentId { get; set; }
        public string TrackingNumber { get; set; }
        public string FrayteNumber { get; set; }
        public string TrackingDescription { get; set; }
        public string TrackingDescriptionCode { get; set; }
        public string TrackingMode { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
    }
}
