//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpressDriverManifest
    {
        public int ExpressDriverManifestId { get; set; }
        public Nullable<int> ExpressManifestId { get; set; }
        public string DriverManifestNumber { get; set; }
        public string DriverManifestBarCode { get; set; }
        public byte[] PodSignature { get; set; }
        public Nullable<int> PodBy { get; set; }
        public Nullable<System.DateTime> PodOn { get; set; }
        public string SignedBy { get; set; }
    }
}
