//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpressAWB
    {
        public int ExpressAWBId { get; set; }
        public string AWBNumber { get; set; }
        public string AWBDocumentName { get; set; }
        public int ExpressShipmentId { get; set; }
        public System.DateTime ScannedOnUtc { get; set; }
        public int ScannedBy { get; set; }
    }
}
