//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Express
    {
        public int ExpressId { get; set; }
        public Nullable<int> OperationZoneId { get; set; }
        public int CustomerId { get; set; }
        public string AWBBarcode { get; set; }
        public int AWBScannedBy { get; set; }
        public System.DateTime AWBScannedOnUtc { get; set; }
        public int ShipmentStatusId { get; set; }
        public Nullable<int> FromAddressId { get; set; }
        public Nullable<int> ToAddressId { get; set; }
        public string PaymentPartyTaxAndDuty { get; set; }
        public string PaymentPartyTaxAndDutyAccountNumber { get; set; }
        public string PacakgeCalculationType { get; set; }
        public Nullable<decimal> ActualWeight { get; set; }
        public Nullable<decimal> DeclaredValue { get; set; }
        public string DeclaredCurrencyCode { get; set; }
        public string ShipmentReference { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public Nullable<int> BagId { get; set; }
        public string FrayteNumber { get; set; }
        public string TrackingNumber { get; set; }
        public Nullable<int> TradelaneShipmentId { get; set; }
        public string IntegrationRequest { get; set; }
        public string IntegrationResponse { get; set; }
        public string LogisticLabel { get; set; }
        public string LogisticLabelImage { get; set; }
        public Nullable<int> HubCarrierServiceId { get; set; }
        public Nullable<int> MasterTrackingDetailId { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.TimeSpan> DeliveryTime { get; set; }
        public string SignedBy { get; set; }
        public Nullable<System.DateTime> PODMailSentOn { get; set; }
        public string AdditionalInfo { get; set; }
        public string ParcelType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string MobileEvent { get; set; }
    }
}
