//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpressDetailPackageLabel
    {
        public int ExpressDetailPackageLabelId { get; set; }
        public int ExpressShipmentDetailId { get; set; }
        public string TrackingNumber { get; set; }
        public string PackageLabelName { get; set; }
        public bool IsDownloaded { get; set; }
    }
}
