//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpressScanAWB
    {
        public int AWBId { get; set; }
        public string PhotoName { get; set; }
        public string AwbBarcodeNo { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ScannedBy { get; set; }
        public Nullable<System.DateTime> ScannedOn { get; set; }
        public string EventCode { get; set; }
    }
}
