//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpressBag
    {
        public int BagId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Courier { get; set; }
        public string BagNumber { get; set; }
        public string BagBarCode { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> HubCarrierId { get; set; }
        public Nullable<int> DriverManifestId { get; set; }
        public Nullable<int> ManifestId { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
