//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelSurCharge
    {
        public int FuelSurChargeId { get; set; }
        public int LogisticServiceId { get; set; }
        public int OperationZoneId { get; set; }
        public decimal FrayteFuelPercent { get; set; }
        public decimal ExpryesFuelPercent { get; set; }
        public Nullable<decimal> DomesticFuelPercent { get; set; }
        public Nullable<decimal> RoadFuelSurcharge { get; set; }
        public System.DateTime FuelMonthYear { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<System.DateTime> MailSendOn { get; set; }
    }
}
