//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HubCarrierService
    {
        public int HubCarrierServiceId { get; set; }
        public int HubCarrierId { get; set; }
        public string ServiceType { get; set; }
        public string ServiceTypeDisplay { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<decimal> MaxWeight { get; set; }
        public string WeightUnit { get; set; }
        public string WeightRoundLogic { get; set; }
        public string TransitTime { get; set; }
        public string LogisticType { get; set; }
        public string Logo { get; set; }
        public string ServiceCode { get; set; }
        public string NetworkCode { get; set; }
        public bool IsActive { get; set; }
    }
}
