//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HubCarrierServiceCountryPostCode
    {
        public int HubCarrierServiceCountryPostCodeId { get; set; }
        public int HubId { get; set; }
        public int HubCarrierServiceId { get; set; }
        public int CountryId { get; set; }
        public string PostCode { get; set; }
    }
}
