//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HubCarrier
    {
        public int HubCarrierId { get; set; }
        public int HubId { get; set; }
        public string Carrier { get; set; }
        public string CarrierService { get; set; }
        public string CutOffTime { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string CompanyName { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Area { get; set; }
        public string PostCode { get; set; }
        public int CountryId { get; set; }
        public string Email { get; set; }
        public string TelephoneNo { get; set; }
        public string MobileNo { get; set; }
        public string TermAndCondition { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
