//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogisticServiceDetail
    {
        public int LogisticServiceDetailId { get; set; }
        public int LogisticServiceId { get; set; }
        public string PackageType { get; set; }
        public string PackageTypeDisplay { get; set; }
        public string ParcelType { get; set; }
        public string ParcelTypeDisplay { get; set; }
        public string ServiceType { get; set; }
        public string ServiceTypeDisplay { get; set; }
        public string AddressType { get; set; }
        public string AddressTypeDisplay { get; set; }
        public string PODType { get; set; }
        public string PODTypeDisplay { get; set; }
    }
}
