//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogisticIntegration
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Url { get; set; }
        public string Mode { get; set; }
        public string InetgrationKey { get; set; }
        public string Name { get; set; }
        public string AppVersion { get; set; }
        public string AppId { get; set; }
        public string UserAgent { get; set; }
        public int OperationZoneId { get; set; }
        public string VoidApiUrl { get; set; }
        public string PickupApiUrl { get; set; }
        public string LabelApiUrl { get; set; }
    }
}
