//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogisticServiceCourierAccount
    {
        public int LogisticServiceCourierAccountId { get; set; }
        public int LogisticServiceId { get; set; }
        public string IntegrationAccountId { get; set; }
        public string AccountNo { get; set; }
        public string AccountCountryCode { get; set; }
        public string Description { get; set; }
        public string ColorCode { get; set; }
        public bool IsActive { get; set; }
    }
}
