//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogisticServiceAddOn
    {
        public int LogisticServiceAddOnId { get; set; }
        public int LogisticServiceId { get; set; }
        public Nullable<int> LogisticServiceWeightLimitId { get; set; }
        public decimal WeightFrom { get; set; }
        public decimal WeightTo { get; set; }
        public int LogisticServiceZoneId { get; set; }
        public decimal AddOnRate { get; set; }
        public string AddOnCurrency { get; set; }
    }
}
