//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogisticServiceWeight
    {
        public int LogisticServiceWeightId { get; set; }
        public int LogisticServiceShipmentTypeId { get; set; }
        public decimal WeightFrom { get; set; }
        public decimal WeightFromDisplay { get; set; }
        public decimal WeightTo { get; set; }
        public decimal WeightToDisplay { get; set; }
        public string UOM { get; set; }
        public string WeightUnit { get; set; }
        public string ParcelType { get; set; }
        public string ParcelDisplayType { get; set; }
        public string PackageType { get; set; }
        public string PackageDisplayType { get; set; }
    }
}
