//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogisticServiceBaseRateCardHistory
    {
        public int LogisticServiceBaseRateCardHistoryId { get; set; }
        public int LogisticServiceId { get; set; }
        public int ReportYear { get; set; }
        public string ReportFileName { get; set; }
    }
}
