//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogisticServiceZonePostCode
    {
        public int LogisticServiceZonePostCodeId { get; set; }
        public string PostCode { get; set; }
        public Nullable<int> YodelLogisticServiceZoneId { get; set; }
        public Nullable<int> HermesLogisticServiceZoneId { get; set; }
        public Nullable<int> UKMailLogisticServiceZoneId { get; set; }
        public Nullable<int> DHLLogisticServiceZoneId { get; set; }
        public Nullable<int> DPDLogisticServiceZoneId { get; set; }
    }
}
