//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogisticServiceWeightLimit
    {
        public int LogisticServiceWeightLimitId { get; set; }
        public int LogisticServiceId { get; set; }
        public string ParcelType { get; set; }
        public string PackageType { get; set; }
        public decimal WeightLimit { get; set; }
        public string WeightUnit { get; set; }
        public Nullable<decimal> AddOnApplyAfterWeight { get; set; }
        public Nullable<decimal> BaseRateTillWeight { get; set; }
        public Nullable<decimal> WeightFrom { get; set; }
        public Nullable<decimal> WeightTo { get; set; }
        public string BusinessRuleApply { get; set; }
        public Nullable<bool> AddOnPerPoint5KgApply { get; set; }
        public Nullable<bool> AddOnPer1KgApply { get; set; }
        public Nullable<bool> AddOnPer10KgApply { get; set; }
        public string AddOnDescription { get; set; }
        public Nullable<bool> AddOnPer5KgApply { get; set; }
    }
}
