//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogisticServiceThirdPartyMatrix
    {
        public int LogisticServiceThirdPartyMatrixId { get; set; }
        public int OperationZoneId { get; set; }
        public int FromLogisticServiceZoneId { get; set; }
        public int ToLogisticServiceZoneId { get; set; }
        public int ApplyLogisticServiceZoneId { get; set; }
    }
}
