//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogisticServiceZone
    {
        public int LogisticServiceZoneId { get; set; }
        public int LogisticServiceId { get; set; }
        public string ZoneName { get; set; }
        public string ZoneDisplayName { get; set; }
        public string ZoneColor { get; set; }
        public string ReportZoneDisplay { get; set; }
        public int TransitTime { get; set; }
    }
}
