//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterTracking
    {
        public int MasterTrackingId { get; set; }
        public string ModuleType { get; set; }
        public string EventName { get; set; }
        public string EventKey { get; set; }
        public string EventKeyDisplay { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<bool> IsOnlyForTracking { get; set; }
        public Nullable<bool> IsOnlyMAWBTracking { get; set; }
    }
}
