//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterTrackingDetail
    {
        public int MasterTrackingDetailId { get; set; }
        public int MasterTrackingId { get; set; }
        public string EventKey { get; set; }
        public string EventDisplay { get; set; }
        public bool IsExternal { get; set; }
        public bool IsDefault { get; set; }
        public string EventMessage { get; set; }
    }
}
