//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterTrackingConfiguration
    {
        public int MasterTrackingConfigurationId { get; set; }
        public string ModuleType { get; set; }
        public string TrackingKey { get; set; }
        public int MobileEventConfigurationId { get; set; }
        public bool IsActive { get; set; }
    }
}
