//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAWBCustomized
    {
        public int MAWBCustomizedeFieldID { get; set; }
        public Nullable<int> TradelaneShipmentId { get; set; }
        public string IssuingCarriersAgentNameandCity { get; set; }
        public string DeclaredValueForCarriage { get; set; }
        public string DeclaredValueForCustoms { get; set; }
        public string ValuationCharge { get; set; }
        public string Tax { get; set; }
        public string TotalOtherChargesDueAgent { get; set; }
        public string TotalOtherChargesDueCarrier { get; set; }
        public string OtherCharges { get; set; }
        public string ChargesAtDestination { get; set; }
        public string TotalCollectCharges { get; set; }
        public string CurrencyConversionRates { get; set; }
        public string TotalPrepaid { get; set; }
        public string TotalCollect { get; set; }
        public string HandlingInformation { get; set; }
        public string AgentsIATACode { get; set; }
        public string AccountNo { get; set; }
    }
}
