//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileUserConfiguration
    {
        public int MobileUserConfigurationId { get; set; }
        public int MasterTrackingDetailId { get; set; }
        public int UserId { get; set; }
        public bool IsDefalut { get; set; }
        public string EventMessage { get; set; }
        public bool IsActive { get; set; }
        public bool IsExternal { get; set; }
    }
}
