//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleLevelDetail
    {
        public int ModuleLevelDetailId { get; set; }
        public int ModuleLevelId { get; set; }
        public string SubModuleName { get; set; }
        public string MultilingualKey { get; set; }
        public string Route { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public bool IsParent { get; set; }
        public Nullable<int> OrderNumber { get; set; }
    }
}
