//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleLevel
    {
        public int ModuleLevelId { get; set; }
        public string ModuleName { get; set; }
        public string MultilingualKey { get; set; }
        public Nullable<bool> IsChildShow { get; set; }
        public Nullable<int> OperationZoneId { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string ModuleType { get; set; }
    }
}
