//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationZoneExchangeRate
    {
        public int OperationZoneExchangeRateId { get; set; }
        public int OperationZoneId { get; set; }
        public string CurrencyCode { get; set; }
        public decimal ExchangeRate { get; set; }
        public string ExchangeType { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> MailSendOn { get; set; }
    }
}
