//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCatalogDetailUSA
    {
        public int ProductCatalogDetailUSAId { get; set; }
        public int ProductCatalogId { get; set; }
        public int HubId { get; set; }
        public string Reference { get; set; }
        public string InternalAccountnumber { get; set; }
        public string WeightUOM { get; set; }
        public string ItemHSCode { get; set; }
        public string CustomEntryType { get; set; }
        public string CustomTotalValue { get; set; }
        public string CustomTotalVAT { get; set; }
        public string CustomDuty { get; set; }
        public string Pieces { get; set; }
        public string ItemValue { get; set; }
        public string CustomCommodityMap { get; set; }
        public string ECommerceShipmentId { get; set; }
        public string Currency { get; set; }
    }
}
