//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCatalogDetailJapan
    {
        public int ProductCatalogDetailJAPANId { get; set; }
        public int ProductCatalogId { get; set; }
        public int HubId { get; set; }
        public string No { get; set; }
        public string CodeKg { get; set; }
        public string DeclaredValueOfCustom { get; set; }
        public string Currency { get; set; }
        public string Origin { get; set; }
        public string OriginCode { get; set; }
    }
}
