//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCatalogDetailSWISS
    {
        public int ProductCatalogDetailSWISSId { get; set; }
        public int ProductCatalogId { get; set; }
        public int HubId { get; set; }
        public string ReferenceInvoiceNR { get; set; }
        public string Currency { get; set; }
        public string VersendLand { get; set; }
        public string Anzahl { get; set; }
        public string Netto { get; set; }
        public string Brutto { get; set; }
        public string TarifCode { get; set; }
        public string Value { get; set; }
        public string OriginCountry { get; set; }
        public string PacType { get; set; }
        public string PacQty { get; set; }
        public string ZeichenPackstucke { get; set; }
        public string ArtVorpapier { get; set; }
        public string ZeichenVorpapier { get; set; }
    }
}
