//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCatalogDetailUK
    {
        public int ProductCatalogDetailUKId { get; set; }
        public int ProductCatalogId { get; set; }
        public int HubId { get; set; }
        public string Vat { get; set; }
        public string Pce { get; set; }
        public string Number { get; set; }
        public string TCode { get; set; }
        public string Currency { get; set; }
        public string Value { get; set; }
        public string Weblink { get; set; }
    }
}
