//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public int PurchaseOrderId { get; set; }
        public int OperationZoneId { get; set; }
        public int CustomerId { get; set; }
        public int FactoryUserId { get; set; }
        public int FromAddrressId { get; set; }
        public int ToAddrressId { get; set; }
        public int DeaprtureAirportId { get; set; }
        public int ShipmentStatusId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public int HubCarrierServiceId { get; set; }
        public string CareOf { get; set; }
        public int PONumber { get; set; }
        public int StyleNumber { get; set; }
        public string StyleName { get; set; }
        public string ConsignmentNumber { get; set; }
        public string ShipmentType { get; set; }
        public string DeliveryType { get; set; }
        public int IncotermId { get; set; }
        public System.DateTime ExFactoryDate { get; set; }
        public string customField1 { get; set; }
        public string CustomField2 { get; set; }
        public string CustomField3 { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
