//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationShipmentOptionalService
    {
        public int QuotationShipmentOptionalServicesId { get; set; }
        public int QuotationShipmentId { get; set; }
        public int LogisticOptionalServiceId { get; set; }
        public string OptionalServiceCode { get; set; }
    }
}
