//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationShipment
    {
        public int QuotationShipmentId { get; set; }
        public int OpearionZoneId { get; set; }
        public int CustomerId { get; set; }
        public int FromCountryId { get; set; }
        public int ToCountryId { get; set; }
        public string FromPostCode { get; set; }
        public string ToPostCode { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<decimal> TotalEstimatedWeight { get; set; }
        public Nullable<decimal> BaseRate { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public Nullable<decimal> FuelSurCharge { get; set; }
        public Nullable<decimal> AdditionalSurcharge { get; set; }
        public Nullable<decimal> FuelSurchargePercent { get; set; }
        public Nullable<System.DateTime> FuelMonthYear { get; set; }
        public string LogisticType { get; set; }
        public string LogisticCompany { get; set; }
        public string LogisticCompanyDisplay { get; set; }
        public string RateType { get; set; }
        public string RateTypeDisplay { get; set; }
        public string ShipmentType { get; set; }
        public Nullable<int> ShipmentTypeId { get; set; }
        public string IntegrationAccountId { get; set; }
        public string CourierAccountNo { get; set; }
        public string CourierDescription { get; set; }
        public string ParcelServiceType { get; set; }
        public string ParcelType { get; set; }
        public string CurrencyCode { get; set; }
        public string PackageCaculatonType { get; set; }
        public string AddressType { get; set; }
        public string TransitTime { get; set; }
        public Nullable<decimal> ChargeableWeight { get; set; }
    }
}
