//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSetting
    {
        public int ReportSettingId { get; set; }
        public bool IsActive { get; set; }
        public System.TimeSpan ReportTime { get; set; }
        public string ReportSchedule { get; set; }
        public Nullable<System.DateTime> LastRun { get; set; }
        public string ToMail { get; set; }
    }
}
