//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleModule
    {
        public int RoleModuleId { get; set; }
        public int ModuleLevelId { get; set; }
        public int ModuleLevelDetailId { get; set; }
        public int RoleId { get; set; }
        public string Route { get; set; }
        public string Route1 { get; set; }
        public string Route2 { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsDefaultRoute { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
