//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentEasyPostRate
    {
        public int ShipmentEasyPostRateId { get; set; }
        public int ShipmentId { get; set; }
        public string Carrier { get; set; }
        public string EasyPostRateId { get; set; }
        public string EasyPostShipmentId { get; set; }
        public string CarrierAccountId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<bool> DeliveryDateGuaranteed { get; set; }
        public Nullable<int> DeliveryDays { get; set; }
        public Nullable<int> EstDeliveryDays { get; set; }
        public string ListCurrency { get; set; }
        public string ListRate { get; set; }
        public string Mode { get; set; }
        public string Rate { get; set; }
        public string RetailCurrency { get; set; }
        public string RetailRate { get; set; }
        public string Service { get; set; }
    }
}
