//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentHandlerMethod
    {
        public int ShipmentHandlerMethodId { get; set; }
        public string ShipmentHandlerMethodName { get; set; }
        public string ShipmentHandlerMethodDisplay { get; set; }
        public string ShipmentHandlerMethodCode { get; set; }
        public string ShipmentHandlerMethodType { get; set; }
        public string DisplayName { get; set; }
    }
}
