//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentAgentRejection
    {
        public int ShipmentAgentRejectionId { get; set; }
        public int ShipmentId { get; set; }
        public int OriginatingAgentId { get; set; }
        public string RejectionReason { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
