//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentBagDetail
    {
        public int ShipmentBagDetailId { get; set; }
        public int ShipmentBagId { get; set; }
        public string FrayteAWB { get; set; }
        public int CartonQty { get; set; }
        public int ShipmentId { get; set; }
        public string ModuleType { get; set; }
    
        public virtual ShipmentBag ShipmentBag { get; set; }
    }
}
