//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentEasyPost
    {
        public int ShipmentEasyPostId { get; set; }
        public int ShipmentId { get; set; }
        public string HsTariffNumber { get; set; }
        public string ContentsType { get; set; }
        public string ContentsExplanation { get; set; }
        public string RestrictionType { get; set; }
        public string RestrictionComments { get; set; }
        public Nullable<bool> CustomsCertify { get; set; }
        public string CustomsSigner { get; set; }
        public string NonDeliveryOption { get; set; }
        public string EelPfc { get; set; }
        public string Carrier { get; set; }
        public string EasyPostShipmentId { get; set; }
        public string BarcodeURL { get; set; }
        public string BatchMessage { get; set; }
        public string BatchStatus { get; set; }
        public string PostageLabel { get; set; }
        public string TrackingCode { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string StampURL { get; set; }
        public string ShipmentServiceType { get; set; }
    }
}
