//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentCustomDetail
    {
        public int ShipmentCustomDetailId { get; set; }
        public int ShipmentId { get; set; }
        public string ShipmentServiceType { get; set; }
        public string HsTariffNumber { get; set; }
        public string ContentsType { get; set; }
        public string ContentsExplanation { get; set; }
        public string RestrictionType { get; set; }
        public string RestrictionComments { get; set; }
        public Nullable<bool> CustomsCertify { get; set; }
        public string CustomsSigner { get; set; }
        public string NonDeliveryOption { get; set; }
        public string EelPfc { get; set; }
        public string CatagoryOfItem { get; set; }
        public string CatagoryOfItemExplanation { get; set; }
        public string CommodityCode { get; set; }
        public string TermOfTrade { get; set; }
    }
}
