//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentDetail
    {
        public int ShipmentDetailId { get; set; }
        public int ShipmentId { get; set; }
        public string JobNumber { get; set; }
        public string JobStyle { get; set; }
        public string HSCode { get; set; }
        public Nullable<int> CartonQty { get; set; }
        public int Pieces { get; set; }
        public Nullable<decimal> WeightKg { get; set; }
        public Nullable<decimal> Lcms { get; set; }
        public Nullable<decimal> Wcms { get; set; }
        public Nullable<decimal> Hcms { get; set; }
        public string PiecesContent { get; set; }
        public string LabelName { get; set; }
    }
}
