//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentTracing
    {
        public int ShipmentTracingId { get; set; }
        public string Comment { get; set; }
        public System.DateTime CommentDate { get; set; }
        public int ShipmentBagId { get; set; }
    }
}
