//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentEmailService
    {
        public System.Guid ShipmentEmailServiceId { get; set; }
        public int ShipmentId { get; set; }
        public Nullable<System.DateTime> EmailSentDate { get; set; }
        public System.TimeSpan EmailSentTime { get; set; }
        public int ReminderIn { get; set; }
        public string RemindType { get; set; }
        public string EmailTemplateId { get; set; }
        public bool IsRepeatReminder { get; set; }
        public int EmailSentCount { get; set; }
        public Nullable<int> EmailSentToManagerCount { get; set; }
        public string ManagerEmailTemplateId { get; set; }
    }
}
