//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemAlert
    {
        public int SystemAlertId { get; set; }
        public string Heading { get; set; }
        public string Description { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.TimeSpan FromTime { get; set; }
        public System.DateTime ToDate { get; set; }
        public System.TimeSpan ToTime { get; set; }
        public bool IsActive { get; set; }
        public int OperationZoneId { get; set; }
        public int TimeZoneId { get; set; }
    }
}
