//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackingDetail
    {
        public int TrackingDetailId { get; set; }
        public Nullable<int> ShipmentId { get; set; }
        public string ModuleType { get; set; }
        public string EventCode { get; set; }
        public string EventDescription { get; set; }
        public Nullable<bool> IsMissing { get; set; }
        public Nullable<int> MobileEventConfigurationId { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Lattitude { get; set; }
        public string Longitude { get; set; }
    }
}
