//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackingMileStone
    {
        public int TrackingMileStoneId { get; set; }
        public string MileStoneKey { get; set; }
        public string Description { get; set; }
        public int OrderNumber { get; set; }
        public int ShipmentHandlerMethodId { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOnUtc { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
