//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradelaneShipmentHawb
    {
        public int HawbId { get; set; }
        public string HawbNumber { get; set; }
        public Nullable<int> TradelaneShipmentId { get; set; }
        public Nullable<bool> IsPrinted { get; set; }
        public Nullable<System.DateTime> PrintedOn { get; set; }
        public Nullable<int> PrintedBy { get; set; }
        public Nullable<bool> IsScanned { get; set; }
        public Nullable<int> ScannedBy { get; set; }
    }
}
