//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradelaneShipmentTracking
    {
        public int TradelaneShipmentTrackingId { get; set; }
        public int TradlaneShipmentId { get; set; }
        public string TrackingCode { get; set; }
        public string TrackingDescription { get; set; }
        public string AirportCode { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> Pieces { get; set; }
        public string FlightNumber { get; set; }
    }
}
