//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradelaneShipmentDocument
    {
        public int TradelaneShipmentDocumentId { get; set; }
        public int TradelaneShipmentId { get; set; }
        public string DocumentType { get; set; }
        public string DocumentName { get; set; }
        public string DocumentNameDisplay { get; set; }
        public int UploadedBy { get; set; }
        public System.DateTime UploadedOnUtc { get; set; }
        public Nullable<int> RevisionNumber { get; set; }
    }
}
