//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradelaneShipment
    {
        public int TradelaneShipmentId { get; set; }
        public int OperationZoneId { get; set; }
        public int CustomerId { get; set; }
        public Nullable<System.Guid> CustomerConfirmationCode { get; set; }
        public int ShipmentStatusId { get; set; }
        public int FromAddressId { get; set; }
        public int ToAddressId { get; set; }
        public string ShipperAdditionalNote { get; set; }
        public string ReceiverAdditionalNote { get; set; }
        public Nullable<int> NotifyPartyAddressId { get; set; }
        public string NotifyPartyAdditionalNote { get; set; }
        public bool IsNotifyPartySameAsReceiver { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOnUtc { get; set; }
        public string FrayteNumber { get; set; }
        public string PackageCalculatonType { get; set; }
        public string LogisticType { get; set; }
        public string DepartureAirportCode { get; set; }
        public string DestinationAirportCode { get; set; }
        public Nullable<int> ShipmentHandlerMethodId { get; set; }
        public string ShipmentReference { get; set; }
        public string ShipmentDescription { get; set; }
        public decimal DeclaredValue { get; set; }
        public string DeclaredCurrencyCode { get; set; }
        public Nullable<int> AirlineId { get; set; }
        public Nullable<decimal> TotalEstimatedWeight { get; set; }
        public Nullable<decimal> DeclaredCustomValue { get; set; }
        public Nullable<decimal> InsuranceAmount { get; set; }
        public string CertificateOfOrigin { get; set; }
        public string ExportLicenceNo { get; set; }
        public string PaymentPartyTaxAndDuty { get; set; }
        public string TaxAndDutiesAccountNo { get; set; }
        public string TaxAndDutiesAcceptedBy { get; set; }
        public string Signature { get; set; }
        public Nullable<bool> DangerousGoods { get; set; }
        public string MAWB { get; set; }
        public Nullable<bool> IsAgentMAWBAllocated { get; set; }
        public Nullable<int> MAWBAgentId { get; set; }
        public string ManifestName { get; set; }
        public string BatteryDeclarationType { get; set; }
        public Nullable<int> HAWBNumber { get; set; }
        public Nullable<bool> IsClaim { get; set; }
        public Nullable<bool> IsMawbCorrection { get; set; }
        public string AdditionalInfo { get; set; }
        public Nullable<int> IncotermId { get; set; }
    }
}
