//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradelaneFlightDetail
    {
        public int TradelaneFlightDetailId { get; set; }
        public Nullable<int> TradelaneShipmentId { get; set; }
        public string FlightNumber { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public string DepartureAirportCode { get; set; }
        public string ArrivalAirportCode { get; set; }
        public Nullable<int> Pieces { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public Nullable<decimal> TotalVolume { get; set; }
        public string BookingStatus { get; set; }
    }
}
