//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradelaneShipmentAllocation
    {
        public int TradelaneShipmentAllocationId { get; set; }
        public Nullable<int> TradelaneShipmentId { get; set; }
        public string LegNum { get; set; }
        public string FlightNumber { get; set; }
        public string MAWB { get; set; }
        public Nullable<int> AgentId { get; set; }
        public Nullable<int> TimezoneId { get; set; }
        public Nullable<int> AirlineId { get; set; }
        public Nullable<System.DateTime> EstimatedDateofArrival { get; set; }
        public Nullable<System.DateTime> EstimatedDateofDelivery { get; set; }
        public Nullable<System.DateTime> CreatedOnUTC { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
