//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradelaneUserTrackingConfiguration
    {
        public int TradelaneUserTrackingConfigurationId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> TrackingMileStoneId { get; set; }
        public string OtherMethod { get; set; }
        public bool IsEmailSend { get; set; }
    }
}
