//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tradelane
    {
        public int TradelaneId { get; set; }
        public int OriginatingAgentId { get; set; }
        public int OriginCountryId { get; set; }
        public int DestinationAgentId { get; set; }
        public int DestinationCountryId { get; set; }
        public Nullable<bool> Direct { get; set; }
        public Nullable<bool> Deffered { get; set; }
        public Nullable<int> CarrierId { get; set; }
        public string TransitTime { get; set; }
    }
}
