//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradelaneShipmentDetail
    {
        public int TradelaneShipmentDetailId { get; set; }
        public int TradelaneShipmentId { get; set; }
        public int CartonValue { get; set; }
        public string CartonNumber { get; set; }
        public decimal Length { get; set; }
        public decimal Width { get; set; }
        public decimal Height { get; set; }
        public decimal Weight { get; set; }
        public string HAWB { get; set; }
        public string SONumber { get; set; }
        public Nullable<bool> IsScaned { get; set; }
        public Nullable<int> FromAddressId { get; set; }
        public Nullable<int> ToAddressId { get; set; }
        public Nullable<int> NotifyPartyAddressId { get; set; }
        public Nullable<bool> IsNotifyPartySameAsReceiver { get; set; }
    }
}
