//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAdditional
    {
        public int UserId { get; set; }
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public string AccountMail { get; set; }
        public string CreditLimitCurrencyCode { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public string TermsOfThePayment { get; set; }
        public Nullable<int> AccountUserId { get; set; }
        public Nullable<int> DocumentUserId { get; set; }
        public Nullable<int> ManagerUserId { get; set; }
        public Nullable<int> OperationUserId { get; set; }
        public Nullable<int> SalesUserId { get; set; }
        public string TaxAndDuties { get; set; }
        public Nullable<bool> IsDirectBooking { get; set; }
        public Nullable<bool> IsTradelaneBooking { get; set; }
        public Nullable<bool> IsBreakBulkBooking { get; set; }
        public Nullable<bool> IsECommerce { get; set; }
        public Nullable<bool> IsFuelSurCharge { get; set; }
        public Nullable<bool> IsCurrency { get; set; }
        public Nullable<bool> IsShipperTaxAndDuty { get; set; }
        public Nullable<bool> IsAllowRate { get; set; }
        public Nullable<bool> IsExpressSolutions { get; set; }
        public Nullable<bool> IsWarehouseTransport { get; set; }
        public Nullable<int> DaysValidity { get; set; }
        public string CustomerRateCardType { get; set; }
        public Nullable<bool> IsServiceSelected { get; set; }
        public Nullable<bool> IsWithoutService { get; set; }
        public string APIKey { get; set; }
        public Nullable<bool> IsApiAllow { get; set; }
        public Nullable<System.TimeSpan> FreeStorageTime { get; set; }
        public Nullable<decimal> FreeStorageCharge { get; set; }
        public string FreeStorageCurrencyCode { get; set; }
        public string CustomerType { get; set; }
        public string UserType { get; set; }
        public string DefaultShipmentType { get; set; }
    }
}
