//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserShipmentType
    {
        public int UserShipmentTypeId { get; set; }
        public int UserId { get; set; }
        public Nullable<bool> IsAir { get; set; }
        public Nullable<bool> IsSea { get; set; }
        public Nullable<bool> IsExpryes { get; set; }
    }
}
