//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_GetUnmanifestedShipmentsCount
    {
        public int eCommerceShipmentId { get; set; }
        public int OpearionZoneId { get; set; }
        public int ShipmentStatusId { get; set; }
        public int CustomerId { get; set; }
        public int FromAddressId { get; set; }
        public int ToAddressId { get; set; }
        public string PaymentPartyTaxAndDuties { get; set; }
        public string Reference1 { get; set; }
        public string SpecialInstruction { get; set; }
        public string ContentDescription { get; set; }
        public Nullable<System.TimeSpan> CollectionTime { get; set; }
        public Nullable<System.DateTime> CollectionDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> ShipmentTypeId { get; set; }
        public int WarehouseId { get; set; }
        public Nullable<decimal> BaseRate { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public Nullable<decimal> FuelSurCharge { get; set; }
        public Nullable<decimal> AdditionalSurcharge { get; set; }
        public Nullable<decimal> FuelSurchargePercent { get; set; }
        public Nullable<System.DateTime> FuelMonthYear { get; set; }
        public string ParcelType { get; set; }
        public Nullable<bool> IsPODMailSent { get; set; }
        public Nullable<int> CourierAccountId { get; set; }
        public string LogisticType { get; set; }
        public string LogisticServiceType { get; set; }
        public string CurrencyCode { get; set; }
        public string TrackingDetail { get; set; }
        public string PackageCaculatonType { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.TimeSpan> DeliveryTime { get; set; }
        public string SignedBy { get; set; }
        public string TaxAndDutiesAcceptedBy { get; set; }
        public string FrayteNumber { get; set; }
        public Nullable<int> ManifestId { get; set; }
        public string BarCodeNumber { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public Nullable<System.DateTime> MappedOn { get; set; }
        public Nullable<System.DateTime> ScanedOn { get; set; }
        public Nullable<int> ScanedBy { get; set; }
        public string BookingApp { get; set; }
        public Nullable<System.DateTime> EstimatedDateofDelivery { get; set; }
        public Nullable<System.TimeSpan> EstimatedTimeofDelivery { get; set; }
        public Nullable<bool> IsManifested { get; set; }
        public Nullable<int> CustomManifestId { get; set; }
        public Nullable<System.DateTime> EstimatedDateofArrival { get; set; }
        public Nullable<System.TimeSpan> EstimatedTimeofArrival { get; set; }
        public Nullable<int> eCommerceBagId { get; set; }
        public string LogisticLabel { get; set; }
        public string FrayteLabel { get; set; }
        public Nullable<int> WarehouseLocationId { get; set; }
    }
}
