//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public int WarehouseId { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public int CountryId { get; set; }
        public string LocationName { get; set; }
        public Nullable<decimal> LocationLatitude { get; set; }
        public Nullable<decimal> LocationLongitude { get; set; }
        public Nullable<int> LocationZoom { get; set; }
        public Nullable<decimal> MarkerLatitude { get; set; }
        public Nullable<decimal> MarkerLongitude { get; set; }
        public string LocationMapImage { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public string Email { get; set; }
        public string TelephoneNo { get; set; }
        public string MobileNo { get; set; }
        public string Fax { get; set; }
        public System.TimeSpan WorkingStartTime { get; set; }
        public System.TimeSpan WorkingEndTime { get; set; }
        public int TimeZoneId { get; set; }
        public Nullable<int> WorkingWeekDayId { get; set; }
    }
}
