//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frayte.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingWeekDayDetail
    {
        public int WorkingWeekDayDetailId { get; set; }
        public int WorkingWeekDayId { get; set; }
        public int DayId { get; set; }
        public string DayName { get; set; }
        public string DayHalfTime { get; set; }
    }
}
