truncate table Carrier
truncate table CountryDocument
truncate table Courier
truncate table CustomerShipper
truncate table CustomerTradeLane    
truncate table ReceiverShipper
truncate table Shipment
truncate table ShipmentAgentRejection
truncate table ShipmentDetail
truncate table ShipmentDocument
truncate table ShipmentEmailService
truncate table ShipmentProgress   
truncate table TermAndCondition
truncate table Tradelane      
truncate table [User]
truncate table UserAdditional
truncate table UserAddress
truncate table UserLogin
truncate table UserPublicHoliday
truncate table UserReporting
truncate table UserRole
truncate table Warehouse
truncate table WarehouseUser